import fs from "fs";
import path from "path";
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

async function main() {
  console.log("\n========================================");
  console.log("  EXTRACTING ABIS FOR FRONTEND");
  console.log("========================================\n");

  const contractsDir = path.join(__dirname, "..", "artifacts", "contracts");
  const frontendAbisDir = path.join(__dirname, "..", "..", "frontend", "abis");
  const frontendLibDir = path.join(__dirname, "..", "..", "frontend", "lib");

  // Create abis directory in frontend if it doesn't exist
  if (!fs.existsSync(frontendAbisDir)) {
    fs.mkdirSync(frontendAbisDir, { recursive: true });
    console.log("✓ Created frontend/abis directory");
  }

  // Contracts to extract
  const contracts = [
    { name: "PredictionMarket", file: "PredictionMarket.sol/PredictionMarket.json" },
    { name: "BossBattleGame", file: "BossBattleGame.sol/BossBattleGame.json" },
  ];

  const abis: Record<string, any> = {};

  // Extract ABIs
  for (const contract of contracts) {
    const artifactPath = path.join(contractsDir, contract.file);
    
    if (!fs.existsSync(artifactPath)) {
      console.warn(`⚠ Warning: Artifact not found for ${contract.name}`);
      continue;
    }

    const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf-8"));
    const abi = artifact.abi;

    // Save ABI to frontend/abis
    const abiPath = path.join(frontendAbisDir, `${contract.name}.json`);
    fs.writeFileSync(abiPath, JSON.stringify(abi, null, 2));
    console.log(`✓ Extracted ABI for ${contract.name}`);

    abis[contract.name] = abi;
  }

  // Read deployment addresses for reference
  const deploymentPath = path.join(__dirname, "..", "deployments", "somnia-testnet-latest.json");
  let deploymentAddresses: Record<string, string> = {};

  if (fs.existsSync(deploymentPath)) {
    const deployment = JSON.parse(fs.readFileSync(deploymentPath, "utf-8"));
    deploymentAddresses = {
      PredictionMarket: deployment.contracts.PredictionMarket.address,
      BossBattleGame: deployment.contracts.BossBattleGame.address,
    };
    console.log("✓ Loaded deployment addresses");
    console.log("\n==> Add these to your .env file:");
    console.log(`NEXT_PUBLIC_PREDICTION_MARKET_ADDRESS=${deploymentAddresses.PredictionMarket}`);
    console.log(`NEXT_PUBLIC_BOSS_BATTLE_GAME_ADDRESS=${deploymentAddresses.BossBattleGame}`);
  } else {
    console.warn("⚠ Warning: Deployment file not found.");
  }

  // Create index file for easy imports
  const indexPath = path.join(frontendAbisDir, "index.ts");
  const indexContent = `// Auto-generated ABI exports
// This file is generated by scripts/extract-abis.ts
// Do not edit manually

import PredictionMarketABI from './PredictionMarket.json';
import BossBattleGameABI from './BossBattleGame.json';

export { PredictionMarketABI, BossBattleGameABI };

export const ABIS = {
  PredictionMarket: PredictionMarketABI,
  BossBattleGame: BossBattleGameABI,
} as const;
`;

  fs.writeFileSync(indexPath, indexContent);
  console.log(`✓ Created ABI index file at ${indexPath}`);

  console.log("\n========================================");
  console.log("  EXTRACTION COMPLETE!");
  console.log("========================================\n");

  console.log("==> Extracted ABIs:");
  contracts.forEach((contract) => {
    console.log(`  - ${contract.name}`);
  });

  if (Object.keys(deploymentAddresses).length > 0) {
    console.log("\n==> Contract Addresses (add to .env):");
    Object.entries(deploymentAddresses).forEach(([name, address]) => {
      const envVar = name === 'PredictionMarket' 
        ? 'NEXT_PUBLIC_PREDICTION_MARKET_ADDRESS'
        : 'NEXT_PUBLIC_BOSS_BATTLE_GAME_ADDRESS';
      console.log(`  ${envVar}=${address}`);
    });
  }

  console.log("\n========================================\n");
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

