// Auto-generated ABI exports
// This file is generated by scripts/extract-abis.ts
// Do not edit manually

import PredictionMarketABI from './PredictionMarket.json';
import BossBattleGameABI from './BossBattleGame.json';

export { PredictionMarketABI, BossBattleGameABI };

export const ABIS = {
  PredictionMarket: PredictionMarketABI,
  BossBattleGame: BossBattleGameABI,
} as const;

export type ABI = typeof ABIS[keyof typeof ABIS];
