// Auto-generated ABI exports
// This file is generated by scripts/extract-abis.ts
// Do not edit manually

import PredictionMarketJSON from './PredictionMarket.json';
import SomiTokenJSON from './SomiToken.json';
import BossBattleGameJSON from './BossBattleGame.json';

// Extract just the ABI from Forge's JSON output
export const PredictionMarketABI = PredictionMarketJSON.abi;
export const SomiTokenABI = SomiTokenJSON.abi;
export const BossBattleGameABI = BossBattleGameJSON.abi;

export const ABIS = {
  PredictionMarket: PredictionMarketABI,
  SomiToken: SomiTokenABI,
  BossBattleGame: BossBattleGameABI,
} as const;

export type ABI = typeof ABIS[keyof typeof ABIS];
